---
apiVersion: kueue.x-k8s.io/v1beta1
kind: Workload
metadata:
  name: wl-demo
spec:
  active: true
  podSets:
    - count: 1
      name: main
      template:
        spec:
          containers:
            - name: demo
              resources:
                limits:
                  cpu: "1"
                  memory: 128Mi
                requests:
                  cpu: "1"
                  memory: 128Mi
  priority: 0
  queueName: retry-check-demo
